### ISSUE TITLE
No bundle.js

### ISSUE THREAD

**Issue by pythoneer** [yewstack/yew-wasm-pack-minimal#4]
I cloned the repo installed all the things i think are necessary and get the following errors by

```
wasm-pack build --target web
```

```
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Updating crates.io index
.... omitted downloading and compiling of creates ....
[INFO]: Installing wasm-bindgen...
[INFO]: :-) Done in 53.53s
[INFO]: :-) Your wasm pkg is ready to publish at ./pkg.
```

then started a webserver in the projects root and the Browser is telling me after loading the `index.html`

```
Loading failed for the <script> with source “http://localhost:8080/pkg/bundle.js”.
```

and in fact under /pkg there is no bundle.js like the `index.html` is trying to load

`index.html` from the project

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>Yew</title>
    <script src="/pkg/bundle.js" defer></script>
</head>

<body>
</body>

</html>
```

```
ls -la pkg
```

```
drwxr-xr-x 3 naikon users   4096 24. Nov 19:42 .
drwxr-xr-x 7 naikon users   4096 24. Nov 19:44 ..
-rw-r--r-- 1 naikon users      1 24. Nov 19:42 .gitignore
-rw-r--r-- 1 naikon users   9723 24. Nov 19:42 LICENSE-APACHE
-rw-r--r-- 1 naikon users   1055 24. Nov 19:42 LICENSE-MIT
-rw-r--r-- 1 naikon users    844 24. Nov 19:42 package.json
-rw-r--r-- 1 naikon users   2016 24. Nov 19:42 README.md
drwxr-xr-x 4 naikon users   4096 24. Nov 19:42 snippets
-rw-r--r-- 1 naikon users    149 24. Nov 19:42 yew_wasm_pack_minimal_bg.d.ts
-rw-r--r-- 1 naikon users 152277 24. Nov 19:42 yew_wasm_pack_minimal_bg.wasm
-rw-r--r-- 1 naikon users    427 24. Nov 19:42 yew_wasm_pack_minimal.d.ts
-rw-r--r-- 1 naikon users  26097 24. Nov 19:42 yew_wasm_pack_minimal.js
```

**Comment by jstarry** [comment]
@pythoneer I believe you missed the [Bundle step](https://github.com/yewstack/yew-wasm-pack-minimal#3-temporary-bundle) in the instructions. Try running: `rollup ./main.js --format iife --file ./pkg/bundle.js`

**Comment by pythoneer** [comment]
Indeed. Thanks!

**Comment by MggMuggins** [comment]
Just as an aside sorta related to this issue: the setup process for this stuff has some pitfalls and can burn a lot of time if one doesn't follow the instructions in the readme to the letter. I forgot to pass `--target web` to `wasm-pack` and it led me down a rabbit hole with a `rollup` addon and configuration garbage.

Also worth mentioning that the python webserver stuff in the readme is for python 2, for python 3 use `python -m http.server 8080`.

**Comment by jstarry** [comment]
@MggMuggins thanks the feedback. I updated the python command.

I would like the `wasm-pack` experience to be a lot simpler. Packaging up JS is such a pain and I don't want Yew developer to have to worry about it. If you have any ideas or proposals, please share :)
