### ISSUE TITLE
Panic on Initialization

### ISSUE THREAD

**Issue by Septias** [yewstack/yew-wasm-pack-minimal#9]
Hi,
I've followed all the instructions and didn't change anything, bit I still get this error:

```rust
Encountered a Panic!
Panic error message: attempted to leave type `stdweb::webcore::serialization::SerializedValue` uninitialized, which is invalid
```

**Comment by xfbs** [comment]
Hey @Septias, you should consider changing the title of this issue to be more descriptive, something like: "Encounters a Panic on initialisation". That being said, I'm getting the exact same error:

![yewerror](https://user-images.githubusercontent.com/786420/102759524-86193b80-4374-11eb-8b42-f259bb1123b5.png)

Not sure what is going on here, but it seems as if the error originates from somewhere in the library initialisation code.

**Comment by Septias** [comment]
seems stale
